version: '3.3'

services: 
  frontend:
    image: denidkr24/frontend-vue:origin-deni-app-1-20250303233716 
    container_name: fe-vue-app
    ports:
     - 8087:80
    networks:
     - app-network
  backend: 
    image: denidkr24/be-java-app:origin-deni-app-1-20250303233716 
    container_name: be-java-app
    ports: 
     - 8083:8083
    networks:
     - app-network

networks:
  app-network:
    driver: bridge