version: '3.3'

services:
  # Frontend Service
  frontend:
    image: denidkr24/frontend-vue:origin-deni-app-1-20250124105452
    container_name: frontend-vue-app
    ports:
      - "8087:80" 
    depends_on:
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "monitoring=frontend"

  # Backend Service
  backend:
    image: denidkr24/be-java-app:origin-deni-app-1-20250124105452
    container_name: backend-java-app
    ports:
      - "8083:8083" 
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "monitoring=backend"

  # Loki Service
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - ./loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  # Promtail Service
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app-network

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

  # Node Exporter Service
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9101:9100"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  grafana-data:
