version: '3.3'

services: 
  frontend:
    image: ${DOCKER_HUB}/frontend-vue:${BUILD_TAG}
    container_name: fe-vue-app
    ports:
     - 8087:80
    networks:
     - app-network
  backend: 
    image: ${DOCKER_HUB}/be-java-app:${BUILD_TAG}
    container_name: be-java-app
    ports: 
     - 8083:8083
    networks:
     - app-network

networks:
  app-network:
    driver: bridge