auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  graceful_shutdown_timeout: 5m

ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
